### ISSUE TITLE
netdiff doesn't worth with BMX6-0.1-alpha

### ISSUE THREAD

**Issue by sycophantic** [ninuxorg/netdiff#20]
The recent addition for bmx6 parsing is using the old output, so it doesn't work with newer versions of bmx6.

Here is the output from b6m-jsonp: http://pastebin.com/KmfGnTs7

**Comment by gabri94** [comment]
Probably a NetJson output will be implemented directly in BMX6, let's wait for some updates. Otherwise i'll implement the new parser

**Comment by nemesisdesign** [comment]
Thanks for reporting @sycophantic.
@gabri94 having netjson support directly in bmx would be great. Remember that parsing stuff from existing infrastructure is easier than asking them to upgrade.

**Comment by alfinal** [comment]
@sycophantic : is not using the old output, is using the only JSON output that currently works, you can get that output in your new BMX6 from http://yourip/cgi-bin/luci/qmp/Mesh/topology and parse it.

If @sim6 develop it in next days you'll get a more complete JSON.

**Comment by sycophantic** [comment]
I was using the output from /cgi-bin/b6m-jsonp which doesn't require a luci login

**Comment by nemesisdesign** [comment]
I'm looking forward to see the BMX links in the nodeshot test instance! https://46.101.190.150/

**Comment by gabri94** [comment]
@sycophantic The problem of the b6m-jsonp output is that the nodes are not in a list of dictionaries. they are all in a single dictionary where each node is an attribute with the node name as key.
I don't really know how to parse it.

@nemesisdesign  We are waiting for the implementation of netdiff in nodeshot!

**Comment by alfinal** [comment]
@sycophantic if you want to get JSON from http use `curl -d "username=root&password=passwordf&submit=Login" --dump-header headers http://yourip/cgi-bin/luci/qmp/Mesh/topology` and if you want updates put it in cron. That's a trick... we're waiting @sim6 answer or maybe we're going to try to fix and/or parse b6m-jsonp.

**Comment by sycophantic** [comment]
That will work for me for now.  Gives me the data to create a graph.

**Comment by nemesisdesign** [comment]
Does this mean we don't have a issue anymore?

**Comment by sycophantic** [comment]
It can be closed.

**Comment by alfinal** [comment]
"netdiff doesn't worth with BMX6-0.1-alpha" rename to "netdiff doesn't work with b6m-jsonp" but it could be a b6m issue https://gitlab.com/b6m/b6m if it is accepted by b6m developer...

**Comment by nemesisdesign** [comment]
thanks @alfinal, renamed the issue

**Comment by alfinal** [comment]
Ok, but... maybe is not a netdiff issue...

**Comment by nemesisdesign** [comment]
the issue is closed, but having a precise title in the archive of closed issues is good :-)

**Comment by alfinal** [comment]
It's true that currently netdiff doesn't work with b6m-jsonp, so that is not a closed issue.

b6m-jsonp is just a plugin for BMX6-0.1alpha

netdiff is working with some JSON provided by qMp-BMX6-0.1alpha but is not working with b6m-jsonp, I think is better to explain when we're fisically together :S

**Comment by sim6** [comment]
b6m-jsonp is a piece of b6m but not a plugin of bmx6.
Please, could you explain what are you expecting that I develop?

**Comment by alfinal** [comment]
Ok, sorry, b6m-jsonp is the piece of b6m. B6m get data from BMX6-0.1alpha and b6m-jsonp represent that data in a JSON open standard format.

The problem is that we can not parse that data because the nodes are not in a list of dictionaries. They are all in a single dictionary where each node is an attribute with the node name as key.

Is for that reason that netdiff doesn't work with b6m-jsonp.

I'm gonna try to explain it, but I think that  @gabri94 can do it better than me ;) Actually b6m-jsonp offer an output in that way:

    ({
        "BCNPsgMareDeuColl70e0.9B3448FABA424C1D87D8": {
        "originators": [
            {
                "globalId": "BCNPsgMareDeuColl70e0.9B3448FABA424C1D87D8",
                "blocked": 0,
                "primaryIp": "fd66:66:66:e:20c:42ff:fe61:a68b",
    ...
            "b6mLinks": [
            {
                "globalId": "BCNTirso14-472f.DA3240F56BE9CEF22986",
                "viaDev": "wlan1.12",
                "quality": "normal"
            },
            {
                "globalId": "BCNLluisBonifac2-e25f.30C923E505FC15118AFF",
                "viaDev": "wlan1.12",
                "quality": "normal"
            }
    ...

But, to can parse it we need it in a a list of dictionaries, in that way (that's NetJSON):
    {
    "type": "NetworkGraph",
    "protocol": "BMX6",
    "version": "0.1alpha",
    "revision": "d57e387bc35031a799fcbe17f61806de",
    "metric": "???",
    "router_id": "router_id",
    "nodes": [
        {
            "id": "id1",
            "label": "node-A",
            "properties": {
                "hostname": "node1.my.net"
            }
        },
        {
            "id": "id2",
            "label": "node-B",
            "properties": {
                "hostname": "node2.my.net"
            }
        }
    ],
    "links": [
        {
            "source": "id1",
            "target": "id2",
            "weight": 1,
    ...
            }
        }
    ]
}

[NetJSON-network topology](http://pool.wiki.guifi.net/wiki/NetJSON#Network_Graph) is our proposal, it will be a open standard format for encoding the basic building blocks of networking.

Or, at least, we can work (parsing it) if we get the nodes data in a list of dictionaries in order to get a topology. I mean (proposal):
    ....
            "id": "BCNLluisBonifac2-e25f.30C923E505FC15118AFF",
            }
        }
    ],
    "b6mLinks": [
            {
    ....

Instead of (currrent):

    ({
    "BCNLluisBonifac2-e25f.30C923E505FC15118AFF": {
    ...
        "b6mLinks": [
            {

**Comment by alfinal** [comment]
@sim6 just a question:
is this http://109.69.10.243/raval.json an output generated by b6m-jsonp ? (I get it from http://ip/cgi-bin/luci/qmp/Mesh/topology )

**Comment by sim6** [comment]
No, it is generated by bmx6-luci. I understand you want a parser or a system that generates a NetJson. Do you want to hire me or do you expect I develop it as a volunteer? :P

**Comment by nemesisdesign** [comment]
I think any JSON is fine, we can parse it and convert it to NetJSON.
built-in support would be cool, but it would also mean having to upgrade the nodes.

**Comment by alfinal** [comment]
@sim6 we only want to represent current mesh networks, we develop under umbrella of libre-mesh so we invest in BATMAN-adv+BGP development, we don't invest in qMp-BMX6, but we're asking people that develop or had develop in qMp-BMX6 about the present and the future of the project (because there're not much networks working with BMX6 (compared to BGP, OLSR or BATMAN-adv).

@nemesisdesign parser from [bmx6-luci is already done](https://github.com/ninuxorg/netdiff/pull/17), it provide basics that we need. There aren't a problem to upgrade the nodes.

Let's work in links between NetDiff and Nodeshot?

**Comment by sim6** [comment]
@alfinal OK, but I think you didn't answer my question, I guess you are saying you don't hire me because bmx6 isn't popular. Anyway maybe I can help at some point.

**Comment by gabri94** [comment]
@sim6  We are not hiring anyone becuse we are all volunteers. We just want to standardize the 
topology output of the various routing protocol, and no one is paying us to do it.

I haven't unerstood where is the problem of modifying the format that b6m-json returns.
The data that we need are in there, it's only nedded to change the output format.
Each entry of GlobalId is a node and each entry in b6mLinks is a link.

I tryed to look the bash code of b6m-jsonp, but i can't really understand how the output is generated.

**Comment by sim6** [comment]
@gabri94 No problem, maybe I can contribute but to the beat of my free time.

**Comment by nemesisdesign** [comment]
@sim6 it would be great if you had time to read the specification (10-15 min max) at [netjson.org](http://netjson.org) and send some feedback
